include: 
  - '/terraform/Terraform.gitlab-ci.before-script-secrets-vars.yml'
  - '/terraform/Terraform.base.gitlab-ci.job-deploy-without-before-script.yml'

deploy:
  extends: 
    - .deploy
    - .deploy-without-before-script
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
