include: 
  - '/terraform/Terraform.base.gitlab-ci.before-script-secrets-vars.yml'
  - '/terraform/Terraform.base.gitlab-ci.job-destroy-without-before-script.yml'

destroy:
  extends: 
    - .destroy
    - .destroy-without-before-script
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
