include: 
  - '/terraform/Terraform.base.gitlab-ci.before-script-secrets-vars.yml'

destroy:
  extends: .destroy
  needs:
    - vault_tools_sh
    - validate
  dependencies:
    - vault_tools_sh
  environment:
    name:   $ENVIRONMENT
    action: stop
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      when: manual
