include:
  - project: 'packages-and-registries/gitlab-ci.yml'
    file:
      - '/terraform/Terraform.base.gitlab-ci.yml'

variables:
  ENVIRONMENT:       $CI_COMMIT_BRANCH
  TF_STATE_NAME:     $ENVIRONMENT
  TF_ROOT:           ${CI_PROJECT_DIR}
  TF_VAR_api_v4_url: $CI_API_V4_URL
  TF_VAR_project_id: $CI_PROJECT_ID

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
  - if: $CI_COMMIT_REF_PROTECTED != "true"
    variables:
      ENVIRONMENT:  feature
      AUTO_STOP_IN: "15 minutes"
  - when: always
    variables:
      AUTO_STOP_IN: "never"

cache:
  - key: ${CI_PROJECT_NAME}__${TF_ROOT}__${CI_COMMIT_BRANCH}
    paths:
      - $TF_ROOT/.terraform/
