include:
  - '/terraform/Terraform.gitlab-ci.header.yml'
  - '/terraform/Terraform.gitlab-ci.job-fmt.yml'
  - '/terraform/Terraform.gitlab-ci.job-validate.yml'
  - '/terraform/Terraform.gitlab-ci.job-build.yml'
