.before-script-secrets-vars: &before-script-secrets-vars
    - cd $TF_ROOT
    - ${CI_PROJECT_DIR}/vault_secrets.sh secrets/${ENVIRONMENT}.yml >.secrets && . .secrets && rm .secrets
    - >
      if [ -f "${CI_PROJECT_DIR}/environment/default.env" ]; then
        set -a && source ${CI_PROJECT_DIR}/environment/default.env && set +a
      fi
    - >
      if [ -f "${CI_PROJECT_DIR}/environment/${ENVIRONMENT}.env" ]; then
        set -a && source ${CI_PROJECT_DIR}/environment/${ENVIRONMENT}.env && set +a
      fi

.deploy_without_before_script: 
  needs:
    - vault_tools_sh
    - build
  dependencies:
    - vault_tools_sh
    - build
  environment:
    name:         $ENVIRONMENT
    auto_stop_in: $AUTO_STOP_IN
    on_stop:      destroy
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      when: on_success

deploy:
  extends: 
    - .deploy
    - .deploy_without_before_script
  before_script:
    - *before-script-secrets-vars
