include: 
  - '/terraform/Terraform.base.gitlab-ci.job-deploy-without-before-script.yml'

deploy:
  extends: 
    - .deploy_without_before_script
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
