include: 
  - '/terraform/Terraform.gitlab-ci.before-script-secrets-vars.yml'
  - '/terraform/Terraform.base.gitlab-ci.job-deploy-without-before-script.yml'

.before-script-secrets-vars: 
  before_script:
    - cd $TF_ROOT
    - ${CI_PROJECT_DIR}/vault_secrets.sh secrets/${ENVIRONMENT}.yml >.secrets && . .secrets && rm .secrets
    - >
      if [ -f "${CI_PROJECT_DIR}/environment/default.env" ]; then
        set -a && source ${CI_PROJECT_DIR}/environment/default.env && set +a
      fi
    - >
      if [ -f "${CI_PROJECT_DIR}/environment/${ENVIRONMENT}.env" ]; then
        set -a && source ${CI_PROJECT_DIR}/environment/${ENVIRONMENT}.env && set +a
      fi

deploy:
  extends: 
    - .deploy
    - .deploy-without-before-script
  before_script:
    - !reference [.before-script-secrets-vars, before_script]
