include: 
  - '/terraform/Terraform.base.gitlab-ci.job-destroy-without-before-script.yml'

destroy:
  extends: 
    - .destroy_without_before_script
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
