include: 
  - '/terraform/Terraform.gitlab-ci.before-script-secrets-vars.yaml'
  - '/terraform/Terraform.base.gitlab-ci.job-deploy-without-before-script.yml'

deploy:
  extends: 
    - .deploy
    - .deploy-without-before-script
  before_script:
    !reference [.before-script-secrets-vars, before_script]
