include: 
  - '/terraform/Terraform.base.gitlab-ci.before-scripts.yml'

build:
  extends: .build
  needs:
    - vault_tools_sh
    - validate
  dependencies:
    - vault_tools_sh
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
  rules:
    - when: on_success
