.before_script_ssh_prepare_id: 
  before_script:
  - echo "SSH_PRIVATE_KEY" | tr -d '\r' > id
  - chmod g-rwx,o-rwx id
  - echo "SSH_PUBLIC_KEY" | tr -d '\r' > id.pub

.before_script_ssh_generate_id: 
  before_script:
  - ssh-keygen -t ed25519 -N '' -f id >/dev/null 2>&1  
  - chmod g-rwx,o-rwx id

.before_script_ssh_sign_id: 
  before_script:
  - export _VAULT_SSH_SIGNER_PATH=${VAULT_SSH_SIGNER_PATH:-ssh-client-signer/sign/ssh-client-signer-gitlab}
  - export _VAULT_SSH_SIGNER_PRINCIPALS=${VAULT_SSH_SIGNER_PRINCIPALS:-root}
  - ./vault_token.sh $VAULT_SSH_SIGN_ROLE
  - export SSH_KEY_CERT="$(vault write -field=signed_key ${_VAULT_SSH_SIGNER_PATH} valid_principals="$VAULT_SSH_SIGNER_PRINCIPALS" public_key=@./id.pub)"
  - echo "$SSH_KEY_CERT" | tr -d '\r' > id-cert.pub


.before_script_ssh_agent_add_id: 
  before_script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-add id
  - ssh-keyscan $CI_SERVER_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

.before_script_ssh_agent_add_id_passphrase: 
  before_script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - |
    { sleep .1; echo $SSH_PASSPHRASE; } | script -q /dev/null -c 'ssh-add'
  - ssh-keyscan $CI_SERVER_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
