validate:
  extends: .validate
  needs:
    - vault_tools_sh
  dependencies:
    - vault_tools_sh
  before_script:
    - cd $TF_ROOT
    - cat secrets/${ENVIRONMENT}.yml
    - ls -l ${CI_PROJECT_DIR}
    - echo ${CI_PROJECT_DIR}
    # - cat ${CI_PROJECT_DIR}/vault_secrets.sh
    - echo ${CI_PROJECT_DIR}/vault_secrets.sh secrets/${ENVIRONMENT}.yml --markdown
    - ${CI_PROJECT_DIR}/vault_secrets.sh secrets/${ENVIRONMENT}.yml --markdown
  rules:
    - when: always
