include:
  - template: Terraform/Base.latest.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.latest.gitlab-ci.yml
  - '/vault/Vault.tools.gitlab-ci.yml'
  - '/terraform/Terraform.base.gitlab-ci.before-script-secrets-vars.yml'

stages:
  - vault_tools_sh
  - init
  - validate
  - build
  - test
  - deploy
  - cleanup

.fmt:
  extends: .terraform:fmt
  rules:
    - when: always

.validate:
  extends: .terraform:validate
  rules:
    - when: always

.build:
  extends: .terraform:build
  needs:
    - vault_tools_sh
    - validate
  dependencies:
    - vault_tools_sh
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
  rules:
    - when: on_success

.deploy:
  extends: .terraform:deploy
  needs:
    - vault_tools_sh
    - build
  dependencies:
    - vault_tools_sh
    - build
  environment:
    name:         $ENVIRONMENT
    auto_stop_in: $AUTO_STOP_IN
    on_stop:      destroy
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      when: on_success

.destroy:
  extends: .terraform:destroy
  needs:
    - vault_tools_sh
    - validate
  dependencies:
    - vault_tools_sh
  environment:
    name:   $ENVIRONMENT
    action: stop
  before_script:
    - !reference [.before_script_secrets_vars, before_script]
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      when: manual
