validate:
  extends: .validate
  needs:
    - vault_tools_sh
  dependencies:
    - vault_tools_sh
  before_script:
    - cd $TF_ROOT
    - ls -l ${CI_PROJECT_DIR}
    - ${CI_PROJECT_DIR}/vault_secrets.sh secrets/${ENVIRONMENT}.yml --markdown
  rules:
    - when: always
