.before-script-secrets-vars: &before-script-secrets-vars
    - cd $TF_ROOT
    - ${CI_PROJECT_DIR}/vault_secrets.sh secrets/${ENVIRONMENT}.yml >.secrets && . .secrets && rm .secrets
    - >
      if [ -f "${CI_PROJECT_DIR}/environment/default.env" ]; then
        set -a && source ${CI_PROJECT_DIR}/environment/default.env && set +a
      fi
    - >
      if [ -f "${CI_PROJECT_DIR}/environment/${ENVIRONMENT}.env" ]; then
        set -a && source ${CI_PROJECT_DIR}/environment/${ENVIRONMENT}.env && set +a
      fi

include: /terraform/Terraform.base.gitlab-ci.job-deploy-without-before-script.yml

deploy:
  extends: 
    - .deploy
    - .deploy_without_before_script
  before_script:
    - *before-script-secrets-vars
