
prepare_scanning:
  image: 
    name: ubuntu:20.04
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    # install curl
    - apt-get update -y
    - apt-get install curl -y
    # download templates
    - time curl --remote-name https://gitlab.with.de/packages-and-registries/gitlab-ci.yml/-/raw/main/trivy/html.tpl
    - time curl --remote-name https://gitlab.with.de/packages-and-registries/gitlab-ci.yml/-/raw/main/trivy/gitlab.tpl
  cache:
    paths:
      - html.tpl
      - gitlab.tpl

container_scanning:
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  stage: test
  needs:
    - prepare_scanning
  variables:
    # No need to clone the repo, we exclusively work on artifacts.  See
    # https://docs.gitlab.com/ee/ci/runners/README.html#git-strategy
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    TRIVY_CACHE: .trivycache
  script:
    - trivy --version
    # cache cleanup is needed when scanning images with the same tags, it does not remove the database
    - time trivy --clear-cache
    # update vulnerabilities db
    - time trivy --download-db-only --no-progress
    # Build reports
    - time trivy image --exit-code 0 --no-progress --format template --template "@html.tpl" --output gl-container-scanning-report.html "$FULL_IMAGE_NAME"
    - time trivy image --exit-code 0 --no-progress --format template --template "@gitlab.tpl" --output gl-container-scanning-report.json "$FULL_IMAGE_NAME"
    # Prints full report
    - time trivy image --exit-code 0 --no-progress "$FULL_IMAGE_NAME"
    # Fail on critical vulnerabilities
    - time trivy image --exit-code 1 --severity CRITICAL --no-progress "$FULL_IMAGE_NAME"
  cache:
    paths:
      - gl-container-scanning-report.html
      - gl-container-scanning-report.json

pages:
  image: 
    name: ubuntu:20.04
  stage: test
  needs:
    - container_scanning
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir .public
    - cp gl-container-scanning-report.html .public
    - cp gl-container-scanning-report.json .public
    - mv .public public
  cache:
    paths:
      - gl-container-scanning-report.html
      - gl-container-scanning-report.json
  artifacts:
    paths:
      - public