.before_script_install_vault_secrets: 
  before_script:
    - curl --remote-name ${CI_SERVER_URL}/packages-and-registries/devops-ci-artifacts/-/raw/main/vault/vault_secrets.sh
    - chmod +x vault_secrets.sh
    - mv vault_secrets.sh /usr/local/bin

.before_script_install_vault_kv_puts: 
  before_script:
    - curl --remote-name ${CI_SERVER_URL}/packages-and-registries/devops-ci-artifacts/-/raw/main/vault/vault_kv_puts.sh
    - chmod +x vault_kv_puts.sh
    - mv vault_kv_puts.sh /usr/local/bin

.before_script_install_vault_kv2_patches: 
  before_script:
    - curl --remote-name ${CI_SERVER_URL}/packages-and-registries/devops-ci-artifacts/-/raw/main/vault/vault_kv2_patches.sh
    - chmod +x vault_kv2_patches.sh
    - mv vault_kv2_patches.sh /usr/local/bin

.before_script_install_vault_token: 
  before_script:
    - curl --remote-name ${CI_SERVER_URL}/packages-and-registries/devops-ci-artifacts/-/raw/main/vault/vault_token.sh
    - chmod +x vault_token.sh
    - mv vault_token.sh /usr/local/bin

.before_script_install_vault_tools: 
  before_script:
    - !reference [.before_script_install_vault_secrets, before_script]
    - !reference [.before_script_install_vault_kv_puts, before_script]
    - !reference [.before_script_install_vault_kv2_patches, before_script]
    - !reference [.before_script_install_vault_token, before_script]

.before_script_vault_secrets_and_environments: 
  before_script:
    - echo ${ENVIRONMENT}
    - >
      if [ -f "secrets/default.yml" ]; then
        vault_secrets.sh secrets/default.yml >.secrets && . .secrets && rm .secrets
      fi
    - >
      if [ -f "secrets/${ENVIRONMENT}.yml" ]; then
        vault_secrets.sh secrets/${ENVIRONMENT}.yml >.secrets && . .secrets && rm .secrets
      fi
    - >
      if [ -f "$CI_PROJECT_DIR/environment/default.env" ]; then
        set -a && cat $CI_PROJECT_DIR/environment/default.env | envsubst | grep --invert-match --extended-regexp --regexp "=(''|\"\"){0,1}$" --regexp "=(''|\"\"){0,1}\s*#.*$" >.env && cat .env && . .env && rm .env && set +a
      fi
    - >
      if [ -f "$CI_PROJECT_DIR/environment/${ENVIRONMENT}.env" ]; then
        set -a && cat $CI_PROJECT_DIR/environment/${ENVIRONMENT}.env | envsubst | egrep --invert-match --extended-regexp --regexp "=(''|\"\"){0,1}$" --regexp "=(''|\"\"){0,1}\s*#.*$"  >.env && cat .env && . .env && rm .env && set +a
      fi
