vault_secrets_sh:
  stage: vault_secrets_sh
  needs: []
  variables:
    # No need to clone the repo, we exclusively work on artifacts.  See
    # https://docs.gitlab.com/ee/ci/runners/README.html#git-strategy
    GIT_STRATEGY: none
  script:
    - curl --remote-name ${CI_SERVER_URL}/packages-and-registries/devops-ci-artifacts/-/raw/main/vault/vault_secrets.sh
    - chmod +x vault_secrets.sh
  artifacts:
    expire_in: 1h
    paths:
      - vault_secrets.sh
